### ISSUE TITLE
add "stable since" information to docs

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#106]
it'd be cool if each API / feature in the documentation would state since which release it has been stable (i.e. part of the product and supported (non-beta)).

this is e.g. a cool feature of the documentation for the Rust programming language: their docs always state since when something has been stable. random example from their docs: https://doc.rust-lang.org/std/result/enum.Result.html (note the "1.0.0" in the top-right corner for the whole `enum` or "1.0.0 (const: 1.48.0)" further down for a few of the `impl` - the details are not relevant here, it's just about the fact that this information is present everywhere).

rationale: usually when you search for something online you end up on the latest version of the documentation. but equally often you might not be running on that specific version and might not want to / be able to upgrade to the latest version right now (the dream of running always-up-to-date bleeding edge software is often just that: a dream). it is then very helpful if the documentation immediately tells you starting from when a feature was available, so that you can judge whether you can use it (esp. if you're e.g. building something which needs to work with multiple versions of OpenSearch).
it might also be that the documentation on a newer release is more comprehensive (who will bother updating older documentation if it's already correct in a newer version?), so being able to check the latest version and still see that it's the same as in earlier versions helps.

there are of course some things to consider here, e.g. does the specified version state when the API / feature has been introduced or when the last breaking change happened to it (if a breaking change happened to it)?

adding this information right now would be fairly easy: just specify 1.0.0 for everything (i guess we can safely disregard the elasticsearch history before and presume that this information is mainly interesting for the future and everyone will be on opensearch 1.0 or newer). doing it later would be a lot more effort (things will have been introduced after 1.0 and will have to be found again to be correctly flagged accordingly).

**Comment by aetter** [comment]
Hey @rursprung, thanks for the suggestion.

> does the specified version state when the API / feature has been introduced or when the last breaking change happened to it (if a breaking change happened to it)?

From your perspective, which piece of information is the most valuable here?

1. When the API was introduced
1. The last time the API was changed (non-breaking or breaking)
1. The last time we introduced a breaking change

I suspect we can agree that 2) is the least interesting piece of information. Including 1 and 3 is still pretty hard to scan (see mockup below), so ideally, we'd just include just one or the other. I'm in favor of 3, but curious to hear your thoughts.

<img width="1027" alt="mockup" src="https://user-images.githubusercontent.com/9122297/126547080-e8e73433-62c0-46cb-95cc-f46a406b88be.png">

**Comment by rursprung** [comment]
thanks a lot for looking into this and creating a mockup!
 i agree that 2) is the least interesting. i actually like your mockup which combines 1) and 3)! because it might well be that the breaking change was not relevant to you (some parameter got renamed but you don't care about that one) and you just really want to know when the feature was introduced the first time.

and it'd be super cool if these version numbers would then also directly link back to the docs at that version so that you can see the information as of that point in time (e.g. if there was a breaking change you can check the docs of that version and check what changed*)

\* one issue here is however that presumably the docs at version X wouldn't state what changed in version X but would only give the current description. only the changelog for version X would show it and alternatively you could compare the docs of X and X-1 to see what changed. so maybe instead for the last breaking change it should deep-link to the point in the changelog which documents the breaking change?

as for your mockup: since we're using semantic versioning i would presume that 1.2 would never introduce a breaking change - that'd have to be 2.0, right?

**Comment by aetter** [comment]
Thanks a bunch @rursprung. I suspect that we want people reading either a) the latest version of the documentation or b) the version they happen to be running, so I'm not sure about using the labels to link to old versions, but we do plan to eventually add a dropdown for switching documentation version.

> as for your mockup: since we're using semantic versioning i would presume that 1.2 would never introduce a breaking change - that'd have to be 2.0, right?

Correct, yeah. We didn't do a great job adhering to semantic versioning on ODFE (plugins sometimes snuck in breaking changes on minor releases), but I'm hopeful we can be more consistent this time around. Here's what I think is an improvement on the original mockup. Let me know what you think. I'm not a designer, but the general goal is visually unobtrusive and easy to scan. 😄 

<img width="1055" alt="mockup3" src="https://user-images.githubusercontent.com/9122297/126709559-cd79c600-3747-48cc-9cd7-bda312066839.png">

**Comment by dblock** [comment]
I have a dumb question: when can you have something "introduced" that's not stable? AFAIK we shouldn't ever be shipping an unstable API. Therefore I believe the sections should just be "1.0" (since 1.0), and "deprecated in 3.0". I think we don't need "removed in 4.0" since "deprecated in 3.0" means it will likely be removed in 4.0 following semantic versioning.

**Comment by aetter** [comment]
Hey @dblock, I think the key missing bit in that case is when we add a feature and then break it later. So if we have a hypothetical API that we introduce in 2.0 and overhaul in 3.1, a lone tag of "stable since 3.1" might make a reader think that the feature isn't present in their 2.4 cluster.

**Comment by dblock** [comment]
> Hey @dblock, I think the key missing bit in that case is when we add a feature and then break it later. So if we have a hypothetical API that we introduce in 2.0 and overhaul in 3.1, a lone tag of "stable since 3.1" might make a reader think that the feature isn't present in their 2.4 cluster.

That’s not a real scenario I hope :) we would have shipped a broken feature in 2.0? That’s a definite no. In your case the feature is since 2.0. We made it better in 3.1? Great! But we made is stable in 2.0 or we wouldn’t have skipped it. We also are promising we won’t break backward compatibility without proper major version depreciation.

**Comment by aetter** [comment]
I mean, aside from the breaking change in a minor version, sure, I don't see why that example couldn't be real. I've updated the comment. I just mean "stable since" as "the last time a breaking change was introduced," but if your mind immediately jumped to "not experimental" and we don't mind being wordy, we can make the label "last breaking change" or something.

<img width="1035" alt="mockup4" src="https://user-images.githubusercontent.com/9122297/126722402-71dda4fa-1013-4cd2-b895-97c1e1a8ef38.png">

**Comment by dblock** [comment]
@aetter We are going to do our best not to ever be making breaking changes to APIs, AWS-style, I promise. But if we ever do I will debate the fact that the badge should be of some bright red color :)

**Comment by rursprung** [comment]
interesting discussions happening here :)

if there won't ever be a breaking change (i guess that's another discussion for elsewhere, but: while i fully agree that breaking changes should be avoided if ever possible due to the costs for consumers i also believe that they're sometimes necessary to bring a product further if you don't want to be stuck maintaining legacy code 100% of your time) then indeed a lone "stable since" would be enough. but if there's a breaking change (e.g. a parameter has been removed which is no longer necessary in an API (but might have been needed in earlier releases)) then it'd be good to know when this happened.

while we'd all like that everyone is running bleeding-edge in production that's not always the case - and if you're not running the software yourself but instead ship it to a ton of customers which then run it in various environments you try to minimise the impact of a delivery, so you don't want to force them to upgrade OpenSearch just because you decided to use some API call which only exists in the newest version.

as for always looking at the latest version of the docs: in general i look at the docs of the version i'm currently running, so e.g. i'm currently looking at the ES 7.10 docs and not the ES "current" docs. and if you're writing software which needs to be compatible with multiple versions of a product (e.g. OpenSearch) you'll sometimes want to double-check in the older docs to make sure that what you're doing was really properly supported back then or if there were some subtle changes in-between which might not  be obvious from just looking at the latest version.

**Comment by dblock** [comment]
> interesting discussions happening here :)

I like it. And agree with everything you say.

This brings another point, we probably want these badges to be linking to older versions of docs!

We need https://github.com/opensearch-project/documentation-website/issues/103 sooner than later @AMoo-Miki

**Comment by aetter** [comment]
> This brings another point, we probably want these badges to be linking to older versions of docs!

I think it's the opposite, actually. If we expect few breaking changes over time, those labels being links would get progressively worse and worse. If we add 1.0 labels to everything soon (which seems likely), we'll have dozens or hundreds of links back to the oldest, least complete, worst version of the docs, and those links will rarely get updated to anything more recent due to the lack of breaking changes.

If we accept that the core use cases are "my version" and "newest version," I think we can view "comparing whatever version I'm reading to whenever a feature was introduced" as an edge case that readers can still perform by clicking the version dropdown (which admittedly doesn't exist yet). To cover @rursprung's examples:

> you'll sometimes want to double-check in the older docs to make sure that what you're doing was really properly supported back then

Absolutely, but I think the version you'd want to double-check is arbitrary and not necessarily related to when the API was introduced. For example, you might be on 2.4 and want to check the 2.0 documentation.

> or if there were some subtle changes in-between which might not be obvious from just looking at the latest version.

Anything that would cause a call to fail is a breaking change, which we'll (hopefully) catch and note, but I concede that if we make non-breaking additions to an API, it could be useful to compare the latest call to the older call. Still, I think it's an edge case that we optimize for.

**Comment by rursprung** [comment]
fair enough, i concede to @aetter's reasoning for leaving away the links.
but for breaking changes i wonder if it wouldn't make sense to link to the changelog (deep link to the relevant entry) - otherwise you don't know _what_  has been broken in that release.

**Comment by aetter** [comment]
> but for breaking changes i wonder if it wouldn't make sense to link to the changelog (deep link to the relevant entry) - otherwise you don't know _what_ has been broken in that release.

Agreed 100% on breaking changes labels, yeah.

**Comment by aetter** [comment]
Thanks a ton for the idea here @rursprung. I've merged in #117 and added https://github.com/opensearch-project/documentation-website/commit/db86114248921a6e1d7fbceb8d29a742883a1e13 to document how to handle API labels in the future. Closing this issue out.
