### ISSUE TITLE
[DOC] Query DSL - rewrite query type definitions

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#1116]
**What do you want to do?**
 
- [ ] Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
In the Query DSL / Full Text page (https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#convert-text-with-analyzers), most definitions are phrased as "Creates a <<<Lucene query>>> that...". Queries should not be defined by what Lucene query they generate: the definitions should stand on their own. It is useful to reference the Lucene query somewhere, but not as the primary definition of a query type.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by alicejw-aws** [comment]
Hi @macrakis, just to confirm the request: Do you want the individual query types and field options defined? Just want to be sure I'm on the right track with the requirement.
Example: 
Use the `match` query type to specify fields you want returned.
(Instead of current definitions based on query "Creates a boolean query that returns the search term.)
Thanks

**Comment by alicejw-aws** [comment]
Status: in tech review with PM to verify accuracy.
