### ISSUE TITLE
[DOC] SAML ACS Endpoint is Incorrect

### ISSUE THREAD

**Issue by cliu123** [opensearch-project/documentation-website#1683]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
User follows the documentation, but could not configure SAML properly.

The security plugin uses `/_opendistro/_security/saml/acs` instead of `_plugins/_security/saml/acs`. [The documentation](https://opensearch.org/docs/latest/troubleshoot/saml/#check-the-saml-assertion-consumer-service-url) needs to be corrected. (The right URL is documented [in other places](https://opensearch.org/docs/latest/security-plugin/configuration/saml/#opensearch-dashboards-configuration).)

**Comment by Naarcha-AWS** [comment]
@cwillum: Should be an easy fix here.

**Comment by john-eliatra** [comment]
This issue can be closed because the documentation has already been updated to reflect the correct endpoint to use. ie. it now shows 
`/_opendistro/_security/saml/acs`, and no longer shows `_plugins/_security/saml/acs` as can be seen in the [troubleshooting page](https://opensearch.org/docs/latest/troubleshoot/saml/#check-the-saml-assertion-consumer-service-url), which the reporter said needs to be corrected.

[This PR](https://github.com/opensearch-project/documentation-website/pull/2160) seems to be the one where they were talking about it as a bug previously, and they updated the documentation to fix the issue.

**Comment by hdhalter** [comment]
Closing, as this is fixed.
