### ISSUE TITLE
Document ingest pipelines/nodes

### ISSUE THREAD

**Issue by bgdnlp** [opensearch-project/documentation-website#176]
Would it be possible to add some clear and straight forward documentation regarding the subject?

I'm talking about ingest [pipelines](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/ingest.html) and [APIs](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/ingest-apis.html).

I wasn't able to find any dedicated pages for that. There are some references, for example in the _reindex section, but there's no chapter that I could find that explains ingest pipeline or nodes, their role, and how it can replace Logstash for example. Which seems very useful to me, but I'm definitely no expert.

**Comment by lukas-vlcek** [comment]
Hi @bgdnlp, thanks for catching this. There is a general ticket to complete missing REST API documentation #424.

Please [leave a comment](https://github.com/opensearch-project/documentation-website/issues/424#issuecomment-1048872702) in #424 to include missing APIs so that we can close your ticket and track missing documentation under a single ticket.

**Comment by bgdnlp** [comment]
Done and closing this one, thank you.
