### ISSUE TITLE
CRUD operations for indices and mappings

### ISSUE THREAD

**Issue by aetter** [opensearch-project/documentation-website#19]
- Creating indices, all available settings
- Get index
- Updating index settings without reindexing, which can you update?
- Deleting indices
- Creating mappings, all available settings
- Get mapping
- Updating mappings, how does that work?
- Deleting mappings

**Comment by Naarcha-AWS** [comment]
Index CRUD operations are documented here: https://opensearch.org/docs/latest/im-plugin/ism/api/. The mapping CRUD operation we support is documented here: https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/put-mapping/.

Closing this issue for now until we identify more specific gaps in the ISM CRUD operations docs.

**Comment by keithhc2** [comment]
@Naarcha-AWS This issue is actually for documenting the CRUD operations with indexes in general, not ISM. I believe Andrew's intention here was to have an introductory section that broadly goes into how users can interact with indexes with typical operations. But since we have index CRUD operations in the API reference, I'll leave it to you on whether the issue should stay closed.
