### ISSUE TITLE
[BUG] links on old repo opendistro-for-elasticsearch broken.

### ISSUE THREAD

**Issue by kangman** [opensearch-project/documentation-website#247]
**Describe the bug**
documentation from the old repo should be updated to fix the links. .

**To Reproduce**
1. Go to https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/main/release-notes/opendistro-for-elasticsearch-release-notes-1.6.0.md
2. Click on any of the security links
3. See error 404

**Expected behavior**
Should see a page/document rendered.

**Comment by dblock** [comment]
I moved this to documentation-website. We could do redirects for any dead URLs I imagine, but also personally don't have a strong opinion of whether we _must_ fix this.

**Comment by Naarcha-AWS** [comment]
Considering the date of the request, I'm going to go ahead and close this issue for now. We've released so many updates to OpenSearch since the switch from OpenDistro that anyone using OpenDistro should consult newer documentation in OpenSearch. 

Open to reopen this though, if anyone feels passionate about it.
