### ISSUE TITLE
Can an OpenSearch 2.X client talk to OpenSearch 1.X?

### ISSUE THREAD

**Issue by jmfreeman-trellix** [opensearch-project/documentation-website#2741]
https://opensearch.org/docs/latest/clients/java-rest-high-level/ claims:

" The OpenSearch 1.x high-level REST client works with the 1.x versions of OpenSearch."

and https://opensearch.org/docs/1.3/clients/index/ claims:

"All clients are compatible with any version of OpenSearch."

I ask because OpenSearch Java REST High Level Client 1.3.6 imports snakeyaml which appears to have unresolved CVE's reported.

**Comment by jmfreeman-trellix** [comment]
I then also see:

OpenSearch 2.0.0 no longer supports compatibility with legacy clients. Due to breaking changes with REST APIs, some features are not supported when using OpenSearch 1.x clients to connect to OpenSearch 2.0.

...which is true?

**Comment by kolchfa-aws** [comment]
@wbeckler Could you advise how to reconcile these in the docs? Thanks!

**Comment by kolchfa-aws** [comment]
@VachaShah could you help reconcile these statements please? Thanks!

**Comment by VachaShah** [comment]
Hi @jmfreeman-trellix thank you for your question.

The OpenSearch Clients have a compatibility matrix in each repo which represents its compatibility with the server versions. For example, for the [java client](https://github.com/opensearch-project/opensearch-java) - [compatibility matrix](https://github.com/opensearch-project/opensearch-java/blob/main/COMPATIBILITY.md). The 2.0 version in OpenSearch brought in some breaking changes so 1.x clients work with OpenSearch 2.0.0 clusters except some of the features that were removed - this is better stated in the compatibility matrix.

The OpenSearch Rest High Level Client is a little different since its versioning is hand in hand with the OpenSearch versioning. So when the banner says all clients are compatible with any version of OpenSearch, that excludes the rest high level client.

Overall, it is recommended to use the opensearch-java client instead of the rest high level client since it offers many features and the rest high level client is on the verge of deprecation.

I see how the docs might be confusing, we will work on reconciling this information. But I hope for now, I have answered your questions. Let me know if you have any more questions.
