### ISSUE TITLE
[BUG] Missing API documentation for search.

### ISSUE THREAD

**Issue by SamStephens** [opensearch-project/documentation-website#299]
**What is the bug?**

I want documentation of the basic search operation; the OpenSearch version of https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html. Looking though https://github.com/opensearch-project/documentation-website/tree/ecea83707d2576f07ec0b63a54e406eaafcf1b47/_opensearch/rest-api, there's documentation of advanced search features like multi-search and scroll, but none of the basic search operation.

**How can one reproduce the bug?**

Go to https://opensearch.org/docs/latest/opensearch/rest-api/index/
Fail to find any documentation of the search API.

**What is the expected behavior?**

For the API reference to have parity with the ElasticSearch reference.

**What is your host/environment?**
N/A

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
N/A

**Comment by keithhc2** [comment]
Hey @SamStephens, thanks a bunch for reporting the issue! We're in the process of building out our REST API documentation, but since the Search API is an important operation to OpenSearch (for obvious reasons), we hammered that one out, and it's now [live](https://opensearch.org/docs/latest/opensearch/rest-api/search/) on the docs site. Let us know if there are any other issues!
