### ISSUE TITLE
[BUG] search on website doesn't find content which is clearly there

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#324]
**What is the bug?**
the search on the documentation site doesn't find content even if it's present.

**How can one reproduce the bug?**
1. go to https://opensearch.org/docs/latest/opensearch/configuration/
2. verify that the page contains `compatibility.override_main_response_version: true` (in the example at the end)
3. use the "Search..." box on the top of the page to search for "override_main_response_version" (which you've just verified in the step before to be present on this exact page)

**What is the expected behavior?**
the search should find all pages containing this text - which includes the page linked to in this example

**What is your host/environment?**
should be irrelevant. but:
tested on windows 10 using firefox 94.0.2 (64-bit)

**Do you have any screenshots?**
n/a

**Do you have any additional context?**
n/a

**Comment by elfisher** [comment]
@abbashus can you help take a look at this?

**Comment by abbashus** [comment]
@elfisher Taking a look.

**Comment by abbashus** [comment]
The search is working as expected now.

https://user-images.githubusercontent.com/46726078/145530926-f0916c6f-6db9-4e05-83a8-a605f8724aa0.mp4

#### Background and explanation:

We use OpenSearch for the website and documentation search. We use [Edge n-gram token filter](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/analysis-edgengram-tokenfilter.html) in our custom analyzer where the `max_gram` value was set to `20` meaning the following tokens were produced `["com" , "comp", "compa" ... "compatibilty.overri"]`. As a part of this the value was increased to `255` so now the `compatibility.override_main_response_version` is also produced, pointing to the doc we are looking for.

But this still completely did not solved the problem as tokens like `["ove" , "over", ..., "override_main_response_version"]` were not present. This is because of the [Standard tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/analysis-standard-tokenizer.html) that does not split on dot `.`. Also [only one tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analyzer-anatomy.html#analyzer-anatomy-tokenizer) can be used per tokenizer. A workaround to this was to use [multi-field](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html) with a new analyzer with [Pattern tokenizer ](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/analysis-pattern-tokenizer.html) and use that field  along with original field.

**Comment by rursprung** [comment]
thanks for fixing this so fast and explaining the details, @abbashus!

is your fix publicly visible somewhere? i found https://github.com/opensearch-project/project-website-search but it hasn't been updated yet.

i think it'd be great if the search implementation of the website + documentation would be fully open-source (and be maintained in the public repo, not just having the public repo as a mirror of something AWS-internal) - after all, it's the best showcase for running opensearch!

**Comment by abbashus** [comment]
Yes, I will adding the fix to CDK [PR ](https://github.com/opensearch-project/project-website-search/pull/24), the PR is actually still in review.
