### ISSUE TITLE
[FEATURE] Please add doc reference for Painless Language.

### ISSUE THREAD

**Issue by q2dg** [opensearch-project/documentation-website#369]
**Is your feature request related to a problem?**
Currently main doc is still in ElastcSearch site (https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-painless.html) 

**What solution would you like?**
Copy-Paster above pages to OpenSearch Doc site

Thanks!

**Comment by keithhc2** [comment]
Hey @q2dg, thanks a bunch for writing in. At this time, we're not porting over any Elasticsearch documentation; however, we definitely plan to document Painless scripting, which is in our [priorities list](https://github.com/opensearch-project/documentation-website/projects/1). I'm going to close this issue since we're already tracking it in our backlog board, but if you have any input, feel free to re-open the ticket.
