### ISSUE TITLE
[FEATURE] Update the plugin page with releases automatically

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/documentation-website#379]
**Is your feature request related to a problem?**
The [opensearch-plugin](#https://opensearch.org/docs/latest/opensearch/install/plugins/) does not get updated automatically and is a manual process to update which can be easy to miss.

**What solution would you like?**
Whenever a release is performed, the page gets update automatically like the other pages on the website

**Do you have any additional context?**
Currently, the page only lists plugins till `1.2.0` and needs to be updated.

**Comment by JeffH-AWS** [comment]
The plugins page has been updated with a full list of compatible versions. There are currently no plans to automate this documentation. Since it's updated I'm going to close out this issue. Please reopen it, or open a new issue, if there's still an action item that you believe hasn't been addressed.
