### ISSUE TITLE
[DOC]/install-and-configure/install-opensearch/rpm/#step-1-download-and-install-opensearch

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#4217]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [X] Add new documentation
- [X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
RHEL9 users are unable to install the RPM for OpenSearch if they have downloaded it and are installing locally. The only method that works right now is installing via yum and accepting the warning that appears. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Thanks for reporting this, Nate. Can you provide more information or context?

**Comment by nateynateynate** [comment]
We should at the least mention that RHEL9 isn't supported in the documentation so that people aren't left hanging.

**Comment by peterzhuamazon** [comment]
I would propose to have two changes:
1. Adding a chart of OS compatibility so that it stands out and people know which one are we supporting. Simply listing RHEL9 is not support is not ideal imho as there are so many other Linux distros such as latest Debian/Fedora/Ubuntu/Arch that does not support like RHEL9. We do not want user to have the false impression that we officially tested all the generic linux versions.

### Supported OS Chart:
|  OS  | Version   |
|---|---|
| RHEL / CentOS | 7 / 8  | 
|  Rockylinux / AlmaLinux | 8  |
| Ubuntu  | 16.04 / 18.04 / 20.04  |
| Windows  | Server 2019  | 

2. Add the compatibility page (https://opensearch.org/docs/latest/opensearch/install/compatibility/) link to our download page on the right panel, so that users aware these are the only OSes we officially supported.
![image](https://github.com/opensearch-project/documentation-website/assets/65193828/bab09e25-b476-445d-ad7a-8c809d61f6a3)
