### ISSUE TITLE
[BUG] Unable to create the user roles as per the documentation

### ISSUE THREAD

**Issue by lizsnyder** [opensearch-project/documentation-website#439]
Unable to create the user roles as per the documentation.

[Opendistro Documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/)
User is getting error when following the documentation for elasticsearch 6.8. The same command works for ElasticSearch Version 7 or higher.

curl -u elasticsearch:VLn32KAJRPE_pArWH -X PUT "https://vpc-audi-know-dev-audi-7rlcki2egg3kioz4uxpbuxtewe.eu-west-1.es.amazonaws.com/_opendistro/
_security/api/roles/jacknich_role" -H 'Content-Type: application/json' -d'{"cluster_permissions":["cluster_composite_ops","indices_monitor"]}'

{"status":"error","reason":"Invalid configuration","invalid_keys":{"keys":"cluster_permissions"}}
This curl command works but there is no documentation.

curl -X PUT -u username:Password "your_domain/_opendistro/_security/api/roles/testing_role" -H 'Content-Type: application/json' -d'{"cluster":["UNLIMITED"],"tenants":{"admin_tenant":"RW"},"indices":{"*":{"*":["UNLIMITED"]}}}'

**Comment by lizsnyder** [comment]
@Naarcha-AWS this bug is technically for the OpenDistro docs, but I believe it also applies to the OpenSearch docs: https://opensearch.org/docs/latest/security-plugin/access-control/api/#roles

**Comment by everplays** [comment]
Hi there,

This seems very similar to the issue that we are having so I am gonna comment here instead of creating a new issue.

I was wondering if anyone can shed some light into the relation of https://github.com/opensearch-project/documentation-website/pull/362 and the fact that we still have https://github.com/opensearch-project/security/blob/920701e236680b83e8aa25ef5d027884d3cf4768/securityconfig/roles_mapping.yml#L30-L34.

I am particularly interested in knowing if the default users and roles in the docker setup are gonna be the same as what is available in AWS. Basically, we are running the latest versions of opensearch and opensearch-dashboards available from https://hub.docker.com/u/opensearchproject (1.2.4 and 1.2.0 in that order) for our dev and CI. Yet, if we make the following request to create a user:

```bash
curl -XPUT http://localhost:9200/_plugins/_security/api/internalusers/tenant_1 -d '{
    "password": "veryStrong<password>!!1!",
    "opendistro_security_roles": ["tenant_1", "opensearch_dashboards_user"],
    "backend_roles": ["tenant_1", "opensearch_dashboards_user"]
}'
```

it works fine on AWS but with the docker setup, we get this:

```
method [PUT], host [http://localhost:9200], URI [/_plugins/_security/api/internalusers/tenant_test_1], status line [HTTP/1.1 404 Not Found]
{"status":"NOT_FOUND","message":"Role 'opensearch_dashboards_user' is not available for role-mapping."}
```

while the following works for docker and fails on AWS:

```bash
curl -XPUT http://localhost:9200/_plugins/_security/api/internalusers/tenant_1 -d '{
    "password": "veryStrong<password>!!1!",
    "opendistro_security_roles": ["tenant_1", "kibana_user"],
    "backend_roles": ["tenant_1", "kibana_user"]
}'
```

My guess is that the configuration files living in https://github.com/opensearch-project/security/tree/920701e236680b83e8aa25ef5d027884d3cf4768/securityconfig are not the same as what's used in AWS but something else could be wrong that I am missing.

**Comment by hdhalter** [comment]
According to our maintenance policy, we are no longer supporting documentation for version 1.2.
