### ISSUE TITLE
[FEATURE] Documentation For Frozen Indices

### ISSUE THREAD

**Issue by ahopp** [opensearch-project/documentation-website#453]
**Is your feature request related to a problem?**
When clicking the frozen indices link (see below) in the Advanced Settings (under Stack Management), I see a generic page about [index data](https://opensearch.org/docs/latest/opensearch/index-data). On this page, there is no reference to frozen indices. 

![image](https://user-images.githubusercontent.com/9532728/158633336-6d94242a-5893-4a81-943c-bdb1ea7e76f9.png)

**What solution would you like?**
If I click frozen indices, I should be able to find some relevant information. This would/might include information on freezing and unfreezing an index. 

**What alternatives have you considered?**
None. 

**Do you have any additional context?**
None.

**Comment by elfisher** [comment]
This is not part of OpenSearch, this needs to be removed from OpenSearch Dashboards. @ahopp should we transfer this to the Dashboards repo or open a different issue there?

**Comment by ahopp** [comment]
If that's the case, we should move this to the Dashboards repo and kill the reference in the CX. My assumption is that we'd need to validate the setting/capability is deprecated properly. 

@kavilla can you move this to Dashboards?

**Comment by kavilla** [comment]
Seems like the docs do have mention of support for frozen indices https://opensearch.org/docs/latest/opensearch/rest-api/search/.

I think the ask here is instead of the link clicked on `frozen indices` opening to the generic definition of index data it leads directly to frozen index. On the OpenSearch Dashboards reference, if we dont have a replacement link, we try our best to send folks to a slightly relevant location. If we have no relevant location we send them to the default OpenSearch docs home. If we have a better location for this link to send users too we can move this issue to our repo and update the link if someone can provide it. If we don't then we should leave this issue in this repo and a frozen index doc added before we create a corresponding OpenSearch Dashboards issue.

However, seems like @elfisher point is that forzen indices are no longer supported in OpenSearch? If that's the case, we can migrate this but I actually haven't seen any post about this in OpenSearch.

**Comment by kavilla** [comment]
I didn't realize you created the first issue sorry @ahopp, let me update the previous statement.

**Comment by kavilla** [comment]
@opensearch-project/opensearch-core

**Comment by andrross** [comment]
OpenSearch has no feature to freeze or unfreeze an index. I believe the description for the "ignore_throttled" parameter on the [search documentation](https://opensearch.org/docs/latest/opensearch/rest-api/search/) should not include the word "frozen".

**Comment by hdhalter** [comment]
Closing this issue.
