### ISSUE TITLE
[DOC] Add conversation search feature

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/documentation-website#4943]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Community developer contributes a new conversation search feature https://github.com/opensearch-project/ml-commons/issues/1150. Plan to release in 2.10 for now.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by austintlee** [comment]
@Naarcha-AWS is there anything we need to meet the RC criteria?

**Comment by Naarcha-AWS** [comment]
Hey @austintlee! Excited for this feature. There's a couple of things you can do to make sure we're ready for release once the RC comes out:

1. Write a draft of the initial documentation in markdown. This makes the tech review process easier since I don't have to source technical specifics on the Conversation API myself. You can submit the draft either as a PR or through this issue.
2. After I receive a draft from you, I can go ahead and edit the draft, which includes testing, grammar, and asking any clarifying questions I might have. Once the draft is in a place we're both happy with, we'll pass it along through the [documentation review process](https://github.com/opensearch-project/documentation-website/blob/main/CONTRIBUTING.md#review-process).

Feel free to reach out to me if you have any more questions.

**Comment by Naarcha-AWS** [comment]
@austintlee: We're going to release the first RC tonight at 5 PM PDT. Any content you can provide would be helpful!

**Comment by HenryL27** [comment]
[Conversation Feature Docs.md](https://github.com/opensearch-project/documentation-website/files/12553916/Conversation.Feature.Docs.md)
Here's some documentation for the memory api and roughly the pipeline part. I'll add the pipeline sections next

**Comment by HenryL27** [comment]
[RAG Search Pipeline Docs.md](https://github.com/opensearch-project/documentation-website/files/12554055/RAG.Search.Pipeline.Docs.md)
Here's the Pipeline section. LMK if there's anything else I can give you
