### ISSUE TITLE
[DOC] List Analyzers Through _cat

### ISSUE THREAD

**Issue by macohen** [opensearch-project/documentation-website#5426]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 This feature gives users the ability to list all analyzers available on their cluster. We are targeting 2.12 for this release.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/5481

cc: @lukas-vlcek (the developer of this feature)

**Comment by lukas-vlcek** [comment]
@macohen I created a PR to add documentation around new API option here https://github.com/opensearch-project/documentation-website/pull/6252
However, the list of text analysis components is **NOT** currently included in `_cat` API because the information does not fit tab separated output very well.

Shall we close this ticket for now? The discussion can still go on and we can reopen if we find good representation of the information for `_cat` API. I am open to any suggestions but currently it is only part of Nodes API.

**Comment by hdhalter** [comment]
Yes, we can close this and revisit when appropriate. Thanks!
