### ISSUE TITLE
Part of options table is occluded by nav [BUG]

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/documentation-website#554]
### What is the bug?
In the [Options section of the Full text query page](https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#options), the Description column of the table of options is occluded by the navigation box. There isn't even a horizontal scroll bar (though that shouldn't be necessary).

### How can one reproduce the bug?
Go to [that section](https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#options).

### What is the expected behavior?
The full width of the table should be visible without scrolling.

### What is your host/environment?
Chrome 100.0.4896.127 on MacOS x86.

### Do you have any screenshots?
![image](https://user-images.githubusercontent.com/847626/166803679-8e3ee8eb-15c1-4d1c-82fe-69e14dd95544.png)

### Do you have any additional context?
_Add any other context about the problem._

**Comment by alicejw-aws** [comment]
i can see this via Chrome as well:

![Screen Shot 2022-05-11 at 11 49 31 AM](https://user-images.githubusercontent.com/88908598/167924103-2f54191f-f1b5-46c3-bce8-1ffaf57c3b32.png)

**Comment by alicejw-aws** [comment]
update: available table width limitation (markdown) - workaround:
root cause: one parameter was very wide and took up too much of available table width: 33 characters. 
workaround: remove that option from table and put its own section below table.
see image of fixed table:
![2022-05-12_09-24-57](https://user-images.githubusercontent.com/88908598/168123780-57aa62a4-e4c0-4ddb-8a51-00071ac10c04.png)

**Comment by hdhalter** [comment]
Hi @alicejw-aws - this was also reported in the 1.3 documentation. Is there a way to make this fix in all previous versions, or is it a manual step for each? https://github.com/opensearch-project/documentation-website/issues/527
