### ISSUE TITLE
[FEATURE] Directly document any known issues with certain remote storage classes (nfs / cifs / smb / s3 / et al)

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/documentation-website#569]
### Is your feature request related to a problem?

_A clear and concise description of what the problem is, e.g. I'm always frustrated when [...]._

Someone needed some feedback regarding any known blockers with any particular storage classes. @dblock mentioned it might be a good idea to document it. 

https://github.com/opensearch-project/documentation-website/issues/566

### What solution would you like?

A section under the documentation, perhaps under 'Configuring OpenSearch' that talks about storage class compatibility. 

### What alternatives have you considered?

Permutative testing to generate the data on my own. 

### Do you have any additional context?

I'm not quite sure if the context of the question was regarding using particular filesystem types as repos for snapshots or just running the OpenSearch and OpenSearch Dashboards stack on it in general.

**Comment by andrross** [comment]
> since Elasticsearch did not recommend the NFS storage class due to latency issues and other factors, seems the same applies to OpenSearch

I believe the linked issue here is talking about using a network file system as the local storage on OpenSearch clusters. As others have stated there is no known blocking issue preventing this setup from being functional, but it is not recommended in all cases for performance reasons. (For reference, the AWS-managed offering of OpenSearch allows provisioning clusters with either EBS storage or local SSD storage)

> I'm not quite sure if the context of the question was regarding using particular filesystem types as repos for snapshots

I don't think the issue is for snapshot repositories. Snapshots are not accessed with the same pattern as data on the local disks and therefore not as performance sensitive.

As for the documentation being discussed here, I think some general guidance would be helpful. Something along the lines of "Using a network file system for node storage is not recommended for mission-critical applications. For best performance it is recommended to use local SSDs."

**Comment by JeffH-AWS** [comment]
Thanks @andrross !  @nateynateynate what are your thoughts? Does simply adding that as a disclaimer somewhere satisfy the ask?  Maybe under configuration wherever we describe how to mount remote storage.
