### ISSUE TITLE
[DOC] better documentation for `/_render/template` API

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/documentation-website#6046]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.**
the `/_render/template` API is barely documented, it is only mentioned in passing and not even in a chapter on its own:
https://github.com/opensearch-project/documentation-website/blob/de9a7ca48c8359f26a60c50ba715c9c413a393a2/_api-reference/search-template.md?plain=1#L213-L218

this should at the very least be a dedicated chapter within that page if not a page on its own (i don't know if you plan on having one page per API - which might be nice - or have them grouped together; if you create a dedicated page it should be linked on the current page so that it can be found easily).

i also noticed that a lot of the API documentation doesn't have the "stable since" information (cf #106) anymore, including this API.
 

**What other resources are available?**
as usual, [ES has a nice page](https://www.elastic.co/guide/en/elasticsearch/reference/current/render-search-template-api.html) on it :)

**Comment by hdhalter** [comment]
Thanks for submitting this issue, @rursprung ! We are turning our focus to missing APIs soon, so we can address this then. In the meantime, if you want to take a stab at documenting it, please do : ). 

I read through the discussion on 'stable since' and it sounded like the consensus was to not use that terminology and instead only document anything breaking?
