### ISSUE TITLE
[FEATURE] OpenSearch and OpenSearch Dashboards images Amazon public ECR gallery

### ISSUE THREAD

**Issue by setiah** [opensearch-project/documentation-website#631]
### Is your feature request related to a problem?
Add documentation on how to use OpenSearch and OpenSearch Dashboards images from Amazon public ECR gallery

### What solution would you like?
Describe how users can run OpenSearch and OpenSearch Dashboards available in Amazon public ECR gallery.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by setiah** [comment]
Thanks @Naarcha-AWS for picking this up. I discussed this with @bbarani last week. @prudhvigodithi can provide some references for documentation here.

**Comment by prudhvigodithi** [comment]
Hey @setiah and @Naarcha-AWS , please check the following information:

Current DockerHub registries 
[opensearchproject](https://hub.docker.com/u/opensearchproject)
 [opensearchstaging](https://hub.docker.com/u/opensearchstaging)

New ECR registries
[public.ecr.aws/opensearchproject](https://gallery.ecr.aws/opensearchproject/)
[public.ecr.aws/opensearchstaging](https://gallery.ecr.aws/opensearchstaging/)

- The naming convention for ECR and DockerHub are similar, so that user can leverage projects `opensearchproject` and `opensearchstaging` to fetch the staging and production images.
Example:
 To pull an image from DockerHub `docker pull opensearchproject/opensearch:2.0.0`
 To pull an image from ECR `docker pull public.ecr.aws/opensearchproject/opensearch:2.0.0`

- All the `opensearchproject` images are kept in sync between dockerHub and ECR.
DockerHub [opensearchproject](https://hub.docker.com/r/opensearchproject/opensearch/tags)
ECR [opensearchproject](https://gallery.ecr.aws/opensearchproject/opensearch)

- To run a OpenSearch cluster and dashboard using ECR images, use images from [public.ecr.aws/opensearchproject](https://gallery.ecr.aws/opensearchproject/)
```
public.ecr.aws/opensearchproject/opensearch:2.0.0
public.ecr.aws/opensearchproject/opensearch-dashboards:2.0.0

To run a cluster
docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" public.ecr.aws/opensearchproject/opensearch:2.0.0
```
Fore more information on using `docker-compose` check https://opensearch.org/docs/latest/opensearch/install/docker/, replace `image:` with `public.ecr.aws/opensearchproject/opensearch:2.0.0` and `public.ecr.aws/opensearchproject/opensearch-dashboards:2.0.0` inside compose file to use ECR public gallery images

- Use the ECR public images for OpenSearch and dashboards that had verified account badge.
Example.
<img width="1181" alt="Screen Shot 2022-06-07 at 8 20 30 AM" src="https://user-images.githubusercontent.com/28733332/172377378-9e439699-8a73-4a13-9e5a-8d581068377c.png">

**Comment by JeffH-AWS** [comment]
@setiah  Is the ask here just to let users know that they can pull down the container image from multiple origins?  Or are we replacing the Docker repo with pointers to the ECR repo?

**Comment by setiah** [comment]
It is to let users know that they can pull down the container images from multiple origins

Also adding related issue on project-website repo for reference - https://github.com/opensearch-project/project-website/issues/862
