### ISSUE TITLE
[DOC] Audit_rest_request_method field missing in audit logs

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#6395]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Input from forum: 

Upon enabling audit logging, the audit_rest_request_method attribute becomes visible for all REST call audit logs. However, the absence of documentation regarding the audit_rest_request_method field raises concerns about its availability and reliability. I kindly request clarification on the availability and usage of the audit_rest_request_method field within the documentation to ensure accurate understanding and utilization. (Found in 2.11)

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://forum.opensearch.org/t/doubtful-about-audit-rest-request-method-field-availability-in-audit-logs/17880

**Comment by scrawfor99** [comment]
I am not entirely sure about he request here; the field `audit_rest_request_method` provides the REST request method/call type for each of the requests. This will be the typical `PUT`, `POST`, `GET`, etc. 

I imagine it is not listed here: https://opensearch.org/docs/2.12/security/audit-logs/field-reference/ because it is a common field across all REST requests. It seems like this page is split into different response types and then the fields shared across REST and transport. Since it is not shared with transport but also not unique to a response it probably just was not added. Perhaps we could add a table for universal REST fields or something similar.

**Comment by Naarcha-AWS** [comment]
What do you think about adding that table to this page? https://opensearch.org/docs/latest/api-reference/common-parameters/

**Comment by scrawfor99** [comment]
We can definitely add the information. However, not to sound dismissive (everyone is always learning), I don't know that we want to dedicate parts of the OpenSearch documentation to generic REST request methods. I think adding a note to the audit logging page saying that it is always logged for each request would probably keep the content a bit more OpenSearch-centric. 

Defining specific request methods just borders a bit on re-iterating standard protocols. I would just add a note to the top of the audit page or if get more universally logged fields add a table there.

**Comment by AntonEliatra** [comment]
PR raised https://github.com/opensearch-project/documentation-website/pull/6966
