### ISSUE TITLE
[DOC] Updates to ingestion/Data Prepper documentation

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#6429]
**What do you want to do?**
 Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Update the ingestion documentation to clarify Data Prepper concepts. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
- [x] Update ['ingest pipelines' ](https://opensearch.org/docs/latest/ingest-pipelines/)intro to clarify the difference between these pipelines and Data Prepper. For example, something like "The OpenSearch ingest pipelines run on the OpenSearch cluster. We recommend you only use them for modifications you need to make on the cluster. For other last-mile changes, we recommend using Data Prepper which runs off the cluster." (#6626) and (#6786 )
- [ ] For the individual ingest pipelines pages, describe them as 'index pipelines' since they perform actions on indexes. See https://opensearch.org/docs/latest/ingest-pipelines/get-ingest/ **No change to naming because it will cause code problems. See @gaobinlong comments.**
- [x] From the individual ingest pipelines pages, point them to the DP documentation for further information. **Certain ingest processors aren't available in Data Prepper, including machine learning and vector embedding**
- [x] From the Data Prepper home page, acknowledge that DP is the recommended application for ingestion in OpenSearch. https://opensearch.org/docs/latest/data-prepper/ 
- [ ] Revisit the Tools section to discuss ingestion tools: https://opensearch.org/docs/latest/tools/

**Comment by vagimeli** [comment]
@dlvenable @gaobinlong At your availability, please provide your insights to the above-listed items. I can support the writing efforts once I have a better understanding of how users decide which to use and under what conditions to use them. Thank you, Melissa

**Comment by dlvenable** [comment]
@vagimeli ,

> Update ['ingest pipelines' ](https://opensearch.org/docs/latest/ingest-pipelines/)intro to clarify the difference between these pipelines and Data Prepper. For example, something like "The OpenSearch ingest pipelines run on the OpenSearch cluster. We recommend you only use them for modifications you need to make on the cluster. For other last-mile changes, we recommend using Data Prepper which runs off the cluster."

Regarding the difference between Data Prepper and ingest pipelines, the primary difference is that the ingest pipelines run on the OpenSearch cluster itself. We recommend that users use Data Prepper for any processing that Data Prepper supports. This will reduce load on the cluster and reduce the impact on search workloads.

There are some use-cases that Data Prepper does not support such as ML and vector embedding processors. Users should use ingest pipelines to solve those use-cases.

> For the individual ingest pipelines pages, describe them as 'index pipelines' since they perform actions on indexes. See https://opensearch.org/docs/latest/ingest-pipelines/get-ingest/

We have been seeing confusing between Data Prepper ingestion pipelines and OpenSearch ingest pipelines. Thus, I am in favor of renaming "ingest pipelines" in OpenSearch to "index pipelines." This way, we have two pipeline concepts:
* Ingestion pipelines from Data Prepper
* Index pipelines running on OpenSearch.

> From the individual ingest pipelines pages, point them to the DP documentation for further information.

There are a few ingest pipeline processors with Data Prepper equivalents. We should link users to those. And let users know that they should consider using Data Prepper instead of ingest pipelines.

For example, on the [Grok ingest page](https://opensearch.org/docs/latest/ingest-pipelines/processors/grok/), add a note such as:

"Data Prepper provides a grok processor which runs off the cluster. We recommend that you use Data Prepper's grok processor instead of using an ingest pipeline."

Then link to: https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/grok/

> From the Data Prepper home page, acknowledge that DP is the recommended application for ingestion in OpenSearch. https://opensearch.org/docs/latest/data-prepper/

Agreed.

> Revisit the Tools section to discuss ingestion tools: https://opensearch.org/docs/latest/tools/

Yes, the documentation for ingestion tools should list Data Prepper as the preferred ingestion tool for OpenSearch.

**Comment by vagimeli** [comment]
> @vagimeli ,
> 
> > Update ['ingest pipelines' ](https://opensearch.org/docs/latest/ingest-pipelines/)intro to clarify the difference between these pipelines and Data Prepper. For example, something like "The OpenSearch ingest pipelines run on the OpenSearch cluster. We recommend you only use them for modifications you need to make on the cluster. For other last-mile changes, we recommend using Data Prepper which runs off the cluster."
> 
> Regarding the difference between Data Prepper and ingest pipelines, the primary difference is that the ingest pipelines run on the OpenSearch cluster itself. We recommend that users use Data Prepper for any processing that Data Prepper supports. This will reduce load on the cluster and reduce the impact on search workloads.
> 
> There are some use-cases that Data Prepper does not support such as ML and vector embedding processors. Users should use ingest pipelines to solve those use-cases.
> 
> > For the individual ingest pipelines pages, describe them as 'index pipelines' since they perform actions on indexes. See https://opensearch.org/docs/latest/ingest-pipelines/get-ingest/
> 
> We have been seeing confusing between Data Prepper ingestion pipelines and OpenSearch ingest pipelines. Thus, I am in favor of renaming "ingest pipelines" in OpenSearch to "index pipelines." This way, we have two pipeline concepts:
> 
> * Ingestion pipelines from Data Prepper
> * Index pipelines running on OpenSearch.
> 
> > From the individual ingest pipelines pages, point them to the DP documentation for further information.
> 
> There are a few ingest pipeline processors with Data Prepper equivalents. We should link users to those. And let users know that they should consider using Data Prepper instead of ingest pipelines.
> 
> For example, on the [Grok ingest page](https://opensearch.org/docs/latest/ingest-pipelines/processors/grok/), add a note such as:
> 
> "Data Prepper provides a grok processor which runs off the cluster. We recommend that you use Data Prepper's grok processor instead of using an ingest pipeline."
> 
> Then link to: https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/processors/grok/
> 
> > From the Data Prepper home page, acknowledge that DP is the recommended application for ingestion in OpenSearch. https://opensearch.org/docs/latest/data-prepper/
> 
> Agreed.
> 
> > Revisit the Tools section to discuss ingestion tools: https://opensearch.org/docs/latest/tools/
> 
> Yes, the documentation for ingestion tools should list Data Prepper as the preferred ingestion tool for OpenSearch.

@dlvenable Thank you for this background. I'll work on the OpenSearch Ingest Pipelines documentation to add the clarifications and recommendations. @gaobinlong Do you have additional input?

**Comment by gaobinlong** [comment]
Thanks @vagimeli, firstly, I think the phrase `ingest pipeline` is a well-known name in OpenSearch, and it has been existing for years, all the existing code and documentation use `ingest pipeline`, so it requires big effort to change the name, and also confuses users if we change it . Secondly, in my understanding, here are the main difference between Data prepper and ingest pipeline:

1. Ingest pipeline runs inside OpenSearch so it consumes the resources of the OpenSearch cluster, but Data prepper runs off the OpenSearch cluster, so users need to provide extra resources for Data prepper.
2.  Ingest pipeline only focuses on data pre-processing, but Data prepper can do more work than ingest pipeline, such as fetch data from S3 or Kafka, pre-process the data, and then write the data to OpenSearch. So if users want to transfer the data from one place to another, Data prepper is recommended to use, ingest pipeline cannot complete that work.
3. Ingest pipeline is recommended to be used for small data set and simple data pre-processing, in this case, configuring the ingest pipeline is simple and the overhead on OpenSearch cluster is low, users do not need to purchase machines to run Data prepper and maintain multiple Data prepper nodes. And even for complex data pre-processing, if users still want to use ingest pipeline, dedicated coordinate code or ingest node can be configured in OpenSearch to reduce the overhead on the data node.
4. Data prepper is recommended to be used for large data set and complex data pre-processing, in this case, move the pre-processing  work off OpenSearch cluster can improve the stability of the cluster.
5. Ingest pipeline supports some machine learning related pre-processing such as text embedding and sparse encoding, in this case, ingest pipeline should be used because Data prepper doesn't support that.

**Comment by vagimeli** [comment]
@hdhalter Who is the developer POC for the Tools content?
