### ISSUE TITLE
[DOC] Hierarchical breadcrumb links to the wrong place

### ISSUE THREAD

**Issue by smacrakis** [opensearch-project/documentation-website#6935]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ X] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
On the [significant terms page](
https://opensearch.org/docs/latest/aggregations/bucket/significant-terms/), this appears at the top of the page:

> [Aggregations](https://opensearch.org/docs/latest/aggregations/) / [Bucket aggregations](https://opensearch.org/docs/latest/aggregations/bucket/significant-terms/) / Significant terms

The first link is correct. The second link goes back to the current page, where it should be going to the parent page, "Bucket aggregations".

The same problem appears on all the other 3rd-level pages under Aggregations, e.g., https://opensearch.org/docs/latest/aggregations/bucket/adjacency-matrix/, https://opensearch.org/docs/latest/aggregations/bucket/geotile-grid/ , etc.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
@AMoo-Miki or @peterzhuamazon - Can you please look at our breadcrumb code to see why this is not working? It may be a problem [here](https://github.com/opensearch-project/documentation-website/blob/758bb171dc4c019686d0e745bfbb96662f253296/_layouts/default.html#L152). Thank you.

**Comment by hdhalter** [comment]
Note that it works correctly for Data Prepper docs: https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sources/dynamo-db/

**Comment by hdhalter** [comment]
@Naarcha-AWS - In case you have some insight into why this is happening.

**Comment by AMoo-Miki** [comment]
I have a feeling this is because the pages under Aggregations don't have a `parent`:
https://github.com/opensearch-project/documentation-website/blob/main/_aggregations/bucket/index.md?plain=1
https://github.com/opensearch-project/documentation-website/blob/main/_aggregations/metric/index.md?plain=1
https://github.com/opensearch-project/documentation-website/blob/main/_aggregations/pipeline-agg.md?plain=1

There might be more.

**Comment by hdhalter** [comment]
@AMoo-Miki - I tried to add a parent to each of these topics, but then they don't show up in the TOC: 
<img width="189" alt="image" src="https://github.com/user-attachments/assets/5cfc4dd9-fceb-433c-8b2e-c6a31848ec26">
I'm able to navigate to them and they work properly, I just can't figure out how to get them to appear correctly in the nav pane. I'll push up the PR and maybe someone else can troubleshoot from there. This problem is throughout all of OpenSearch so I'm wondering if it has to do with how many levels we have?
