### ISSUE TITLE
[DOC] Add documentation for remote cluster state publication experiemental feature

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/documentation-website#7347]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Remote cluster state publication is being released as an experimental feature. When this is enabled, the details of the remote cluster state uploaded in blob store will be sent over the transport layer to follower nodes instead of sending the cluster state object.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
Meta issue: https://github.com/opensearch-project/OpenSearch/issues/13683

**Comment by hdhalter** [comment]
Thanks, @soosinha ! What is the ETA for the doc PR? We have the first release candidate today.

**Comment by soosinha** [comment]
RC is moved to 6/11. Will be raising PR before that.

**Comment by shwetathareja** [comment]
Cluster state publication via remote - When it is enabled, the updated cluster state during any updates like creation of an index, put mappings etc. will be published via remote store i.e. cluster manager will provide the remote location and nodes will download the cluster state directly from remote location. As the cluster state grows over time and there are large no. of nodes in the cluster, publishing the state over local transport tends to add lot of overhead in terms of cpu, memory and transport threadpool. This will reduce the overhead on cluster manager node to publish the updated cluster state via remote store to every other node in the cluster instead of local transport.
