### ISSUE TITLE
[DOC] AWS Sigv4 Support for Clients

### ISSUE THREAD

**Issue by brijos** [opensearch-project/documentation-website#814]
### Is your feature request related to a problem?
If people want to connect to an Amazon OpenSearch Service cluster, they have to figure out how to use this client alongside some third-party signing library and/or the AWS SDK, which is non-trivial due to how we (by design) conceal the underlying HTTP requests that the client makes. We should offer IAM signing as an option, just like the OpenSearch CLI does.

Is your feature request related to a problem?
If you want to use this client with an Amazon OpenSearch Service cluster that has IAM authentication rather than basic authentication, it doesn't work.

What solution would you like?
When initializing the client, accept an AWS IAM credential provider and sign requests automatically.

What alternatives have you considered?
An additional signing library for use on top of the client. But given that it would only work with the client, it seems better and easier to just add it to the client.

Do you have any additional context?
https://github.com/opensearch-project/OpenSearch/issues/1400
https://github.com/opensearch-project/opensearch-clients/issues/22

**Comment by Naarcha-AWS** [comment]
@lizsnyder: Do you have any perspective on this? What's the best way to test against the OpenSearch Service.

**Comment by lizsnyder** [comment]
Looks like this text was directly copied from Andrew's requests:

- https://github.com/opensearch-project/opensearch-js/issues/187
- https://github.com/opensearch-project/opensearch-java/issues/55
- https://github.com/opensearch-project/opensearch-py/issues/85

Not sure why it was filed again here. This is not a docs issue. It must be implemented in the clients themselves. Closing.

**Comment by brijos** [comment]
This would have been an issue to update Documentation for when we have completed support for sigv4 for all clients. Is there another mechanism that I should be using?

**Comment by lizsnyder** [comment]
Copying from external convo:

I've updated Python here and am collaborating with someone to get the Java sample updated (since I don't write Java) https://docs.aws.amazon.com/opensearch-service/latest/developerguide/request-signing.html

I've implemented some temporary signers in the Node samples until we have an official built-in one. You can read more in the actual ticket l posted above

At this time the client documentation on the open-source side isn't fully complete like it is in the Elastic docs. That will come as the team hires more writers and continues to fill the gaps in the OpenSearch documentation.

@kolchfa-aws is building out our Client documentation for .NET and Ruby right now. She would be the best person to contact. And of course, keeping logging issues against the documentation-website repo when they relate to Open Source.

**Comment by dblock** [comment]
FYI, there are plenty of remaining issues around Sigv4 signing in the docs, e.g. https://github.com/awsdocs/amazon-opensearch-service-developer-guide/pull/63 and documenting https://github.com/opensearch-project/opensearch-java/pull/177. But those are specific to various clients.
