### ISSUE TITLE
[DOCS] Adds full documentation to opensearch_dashboards.yml

### ISSUE THREAD

**Issue by JeffHuss** [opensearch-project/documentation-website#908]
Related to: https://github.com/opensearch-project/documentation-website/issues/214

Borrowing some of @asfoorial's remarks from the original issue to preserve them:
```
Need full documentation for opensearch_dashboards.yml settings.

This must include every option of every possible attribute in this file.

Previously we used to refer to
https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html but now that OpenSearch is an independent project, it should have its own full set of documentation.

A good starting point https://raw.githubusercontent.com/opensearch-project/OpenSearch/main/distribution/src/config/opensearch.yml and https://raw.githubusercontent.com/opensearch-project/OpenSearch-Dashboards/main/config/opensearch_dashboards.yml. They have some documentation. They just needs to go to opensearch.org.
```

**Comment by JeffH-AWS** [comment]
The original issue was asking for full configuration for `opensearch.yml` and `opensearch_dashboards.yml`.  Given that nobody is actually able to provide an exhaustive list of settings this will require a good amount of research.  Since core and dashboards do not share configuration (as far as I know) then there isn't any overlap of work.

**Comment by hdhalter** [comment]
@ariamarble - for visibility

**Comment by hdhalter** [comment]
This is closed by https://github.com/opensearch-project/documentation-website/pull/4058.
