### ISSUE TITLE
Provide documentation on how to transition from Elasticsearch X-Pack security to OpenSearch security.

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#914]

**Comment by hdhalter** [comment]
@scrawfor99 - Is this something we need to document?

**Comment by scrawfor99** [comment]
HI @hdhalter that is an interesting question....

In theory the Security plugin should be identical up until the OpenSearch 1.0 versions. The problem here is that I am not sure how we can document the process. Really you would need to document just the changes from naming conventions etc. across the two I think.

**Comment by hdhalter** [comment]
Since we have not had any requests for this for this documentation for 2 years, I will close this PR. If this is still needed, feel free to reopen.
